name: Android Build CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Tumia Ubuntu 22.04 badala ya latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-venv \
          git \
          wget \
          curl \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          ninja-build \
          build-essential \
          libsqlite3-dev \
          libreadline-dev \
          libbz2-dev \
          libgdbm-dev \
          tk-dev

    - name: Install Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p android-sdk/cmdline-tools
        unzip -q commandlinetools-linux-8512546_latest.zip -d android-sdk/cmdline-tools
        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
        echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools virtualenv
        pip install buildozer
        pip install cython==0.29.33
        pip install kivy kivymd requests pillow

    - name: Cache Buildozer directories
      uses: actions/cache@v4
      with:
        path: |
          .buildozer
          .buildozer_global
          ~/.buildozer
          ~/.android
          android-sdk
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec', 'main.py') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Initialize Buildozer
      run: |
        buildozer init || true
        buildozer android clean

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
      timeout-minutes: 60

    - name: List built APKs
      run: |
        ls -la bin/ || echo "No bin directory found"

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: micmac-betting-app
        path: bin/*.apk
        retention-days: 30
        if-no-files-found: warn
