name: Android Build CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-venv \
          git \
          wget \
          curl \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          ninja-build \
          build-essential

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install buildozer
        pip install cython==0.29.33

    - name: Cache Buildozer
      uses: actions/cache@v4
      with:
        path: |
          .buildozer
          .buildozer_global
          ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
      timeout-minutes: 60

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: micmac-betting-app
        path: bin/*.apk
        retention-days: 30
