name: Android Build CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install basic system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          git \
          zip \
          unzip \
          openjdk-11-jdk

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.33

    - name: Set environment variables for Buildozer
      run: |
        echo "BUILDOZER_USE_CCACHE=1" >> $GITHUB_ENV
        
    - name: Build APK with Buildozer (let it download everything)
      run: |
        buildozer -v android debug
      timeout-minutes: 60

    - name: List built files
      run: |
        ls -la bin/ || echo "No bin directory"
        find . -name "*.apk" -type f | head -10 || echo "No APK files found"

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: micmac-betting-app
        path: bin/*.apk
        retention-days: 30
        if-no-files-found: warn
