name: Android Build CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-venv \
          git \
          wget \
          curl \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          ninja-build \
          build-essential

    - name: Install Android SDK and Build Tools
      run: |
        # Download Android Command Line Tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk
        unzip -q commandlinetools-linux-9477386_latest.zip -d android-sdk
        mv android-sdk/cmdline-tools android-sdk/cmdline-tools-latest
        
        # Setup environment
        echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/android-sdk/cmdline-tools-latest/bin:$GITHUB_WORKSPACE/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        
        # Accept licenses
        mkdir -p android-sdk/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > android-sdk/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > android-sdk/licenses/android-sdk-preview-license
        
        # Install Android SDK components
        yes | android-sdk/cmdline-tools-latest/bin/sdkmanager --sdk_root=$GITHUB_WORKSPACE/android-sdk \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "cmdline-tools;latest" \
          "ndk;25b"

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install buildozer
        pip install cython==0.29.33
        pip install kivy

    - name: Cache Buildozer
      uses: actions/cache@v4
      with:
        path: |
          .buildozer
          .buildozer_global
          ~/.buildozer
          android-sdk
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Build APK with Buildozer
      run: |
        export ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk
        export ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-sdk/ndk/25b
        export PATH=$GITHUB_WORKSPACE/android-sdk/cmdline-tools-latest/bin:$GITHUB_WORKSPACE/android-sdk/platform-tools:$PATH
        
        buildozer -v android debug
      timeout-minutes: 60

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: micmac-betting-app
        path: bin/*.apk
        retention-days: 30
